cache_file: null
exclude_keywords:
- lindamood
keyword_file: ocr_keywords.xlsx
log_dir: ./logs
ocr_back_pages: false
ocr_crop_top_percent: 100
ocr_engine: paddleocr
output_dir: ./outputs
output_format: pdf
pdf_resize_scale: 1.0
pdf_resolution: 300
# Path to the Poppler binaries used for PDF image extraction
poppler_path: ${POPPLER_PATH:-/path/to/poppler/bin}
preprocess:
  grayscale: false
  rotate: true
rename_original: true
# Example source file or folder
source_path: /path/to/input.pdf
template_dir: template_dir
template_threshold: 0.85
two_page_scan: false
use_roi: false
use_template_fallback: true
