cache_file: null
exclude_keywords:
- lindamood
keyword_file: ocr_keywords.xlsx
log_dir: ./logs
ocr_back_pages: false
ocr_crop_top_percent: 100
ocr_engine: paddleocr
output_dir: ./outputs
output_format: pdf
pdf_resize_scale: 1.0
pdf_resolution: 300
poppler_path: C:/Poppler/poppler-24.08.0/Library/bin
preprocess:
  grayscale: false
  rotate: true
rename_original: true
source_path: C:/Users/brian.atkins/OneDrive - Lindamood Demolition/24-105 PHMS NPC
  - Documents/truck tickets/2025-06-23/export/24-105_2025-06-23_Class2_NTX_WM_22.pdf
template_dir: template_dir
template_threshold: 0.85
two_page_scan: false
use_roi: false
use_template_fallback: true
